from .net_0 import Net0
from .net_1 import Net1
from .net_2 import Net2
from .net_3 import Net3
from .net_4 import Net4
from .net_5 import Net5
from .net_6 import Net6
from .net_7 import Net7
from .net_8 import Net8
from .net_9 import Net9
from .net_10 import Net10